"""changes

Revision ID: d2639cbecf42
Revises: 5ca42d8d075b
Create Date: 2024-05-02 11:33:50.889049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2639cbecf42'
down_revision = '5ca42d8d075b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('description')
        batch_op.drop_index('quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index('quantity', ['quantity'], unique=True)
        batch_op.create_index('description', ['description'], unique=True)

    # ### end Alembic commands ###
